#!/bin/bash

cc daemon.c -o daemon
cc user.c -o user
cc stop.c -o stop
./daemon 5 &
sleep 1
./user &
./user &
./user &
sleep 2
./user &
./user &
./user &
sleep 3
./user &
./user &
./user &
sleep 4
./user &
./user &
sleep 3
./stop
